# NOTE: add the configuration for binding ports

version: "3"

services:
    app:
        # volumes:
        #     - ./src/app:/app
        image: app:local-test
        container_name: app
        restart: unless-stopped
        build: src
        ports:
            - "0.0.0.0:5000:80"
        # environment:
        #     # FLASK_ENV:  'development'
        #     - FLASK_APP= src/app/main.py
        #     # - FLASK_DEBUG=1
        #     # - "RUN=flask run --host=0.0.0.0 --port=5000"
        # # command: flask run --host=0.0.0.0 --port=5000
